### ISSUE TITLE
Table cell justification should have value both

### ISSUE THREAD

**Issue by mattimatti** [drmacro/wordinator#18]
https://github.com/drmacro/wordinator/blob/05119070169c4e3c83f714c231dfe3cb55af8c71/src/main/xsl/html2docx/baseProcessing.xsl#L456

`<xsl:attribute name="align" select="'both'"/>`

**Comment by drmacro** [comment]
The SimpleWP markup uses "justify" because it's the better term--"both" is what the OOXML uses (type ST_Jc).

The Java code was mapping "justify" to "distribute" but I think "both" is the better mapping.

So the SWPX generation transform should not change but I did correct the DOCX generation to use "both" rather than "distribute".

I also updated the XSLT to recognize both "both" and "justify" as synonyms for "justify" in the resulting SWPX document.
