### ISSUE TITLE
Page breaks don't work

### ISSUE THREAD

**Issue by rf2001** [drmacro/wordinator#2]
I've come across a few issues related to page breaks. It looks like page breaks are not implemented at all although I can see them available in rng file.

I've tried the following.

    <section type="nextPage"> (I've also tried type="oddPage", just to test).
    <p ... page-break-before="true">.
    <p ...><break type="page"/>... .

Neither works and the last is not allowed at all as Wordinator doesn't accept a <break> inside a <p> even though it's allowed in the rng.

I'm attaching an swpx file with lots of sections with page breaks.
[bv-ifrs13.zip](https://github.com/drmacro/wordinator/files/3314519/bv-ifrs13.zip)

**Comment by drmacro** [comment]
Note that sections are not implemented for the purpose of creating section-level headers and footers.

**Comment by drmacro** [comment]
The swpx sample is not valid per the RNG: it's missing the required `<body>` element within `<section>` and there are a couple of `<run>` elements not within blocks. However, those issues should not affect the processing you're testing. I've corrected the swpx file for my testing.

**Comment by drmacro** [comment]
Break should not have been allowed as a direct child of `<p>`. Per the Office Open spec, break can only be within run. I've modified the RNG to reflect that. Breaks within runs do work in the current code.

**Comment by drmacro** [comment]
Implementing section-level breaks requires implementing general support for creating section properties, which is not currently in the POI API. Can be done directly in Wordinator but will be a bit more work.

**Comment by drmacro** [comment]
Have implemented handling of sections so that section breaks are generated and should produce the correct page breaks. Implemented setting of page numbers at the section and document level.

Construction of section-specific running heads and feet not yet implemented.

Note that to set the page number format you must use the @format attribute with one of the Word-specific values--the "custom" value is not implemented because it requires translating from XSLT number format strings to the Word equivalent, which is non-trivial.

Adding other section-level properties that are simple settings shouldn't be too hard.

I'm still looking at setting up section-level running heads and feet--the issue is the lack of support in the POI API but it should be possible to do it with the current POI code, I just need to work out the details.

**Comment by drmacro** [comment]
Note that the RNG has changed slightly so be sure to revalidate your SWPX files.

**Comment by rf2001** [comment]
Page breaks work fine now, but there's a side effect. The last line in the last p in a section is now justified. I wonder if this has anything to do with thew following line in the log:
handleBody(): Setting sectPr on last paragraph.
Please see attached (swpx and docx).
[test.zip](https://github.com/drmacro/wordinator/files/3328639/test.zip)

**Comment by drmacro** [comment]
Probably the code should just generate an empty paragraph for each section break.

**Comment by rf2001** [comment]
OK, that seems to nail it.

**Comment by rf2001** [comment]
I've just noticed footers and headers are not generated any more. I'm only using those at document level at the moment. It looks like sections are preventing headers/footers at document level to be generated.

**Comment by drmacro** [comment]
Updated the code to always generate a new empty paragraph for section properties. That should resolve the issue.

**Comment by rf2001** [comment]
You should undo your last change as it generates an unwanted empty line at the end of each section. I've managed to fix that issue by adding and empty p at the end of section body. By empty p I mean `<p/>`. Strangely this doesn't create an empty line at the end of section, it creates a space at the end of the preceding <p>'s last line.

**Comment by drmacro** [comment]
The issue with the justification is a Word "feature", which you can easily explore in a new document.
In Word, if a paragraph is justified, under normal circumstances the last line is *not* justified.
However, if you insert a soft return (ctrl+enter) or *section break* then word *does* justify the last line.
In the case of the docs we're testing with here, the "normal" paragraph style is justified, so section breaks result in justification.
Adding an empty paragraph, even if it has no content, results in at least one white space character.
As far as I can tell there's no way to work around this behavior in word: if the paragraph needs to be justified then if it is followed by a section break and you don't want the last line justified (which you normally don't) then the section break must be on a blank paragraph.
I can implement this one of two ways:
1. Current behavior: generate an empty paragraph for the section break in all cases.
2. Original behavior: put the section break on the last paragraph in the incoming section unless the last object is a table, in which case generate a blank paragraph to hold the section break.

Option 1 requires that you manually generate a break on justified paragraphs that should have the last line justified.
Option 2 requires that you manually generate empty paragraphs when a justified paragraph would be followed by a section break and you don't want the last line justified.
Option 1 seems like the better behavior since it would be rare to want the last line of a justified paragraph justified, which is the default behavior in option 2.
It looks like my test template has justification turned on for the "normal" paragraph style, which is then inherited to all other styles base on "normal".
I doesn't look like the code can determine whether or not a given paragraph is justified if it doesn't refer to a style defined in the document, as opposed to one of the built-in styles.

**Comment by rf2001** [comment]
The current behavior is OK, I just had to remove my own `<p/>` generated at the end of section body. Headers/footers are also OK now.
