### ISSUE TITLE
Generate Table of Contents

### ISSUE THREAD

**Issue by drmacro** [drmacro/wordinator#42]
Enable generation of a Word table of contents using normal Word ToC fields.

**Comment by jcalder1969** [comment]
Hello Eliot:

I am attaching:
- Wordinator_table_of_contents.swpx: this is a mockup sample SWPX file for which a table of contents is desired.  The information pertaining to the table of contents (the styles and levels) is in the first section.
- Wordinator_output_table_of_contents.docx: this is the Wordinator output from the SWPX
- Wordinator_xsl_output_table_of_contents.docx: this document has been updated via XSL (let me know if you would like me to provide this code) to create a table of contents.  The problem is that all the page numbers show as "1" - our customer has a firm requirement that the page numbers be correct.  We have developed a macro that updates the page numbers as the document is opened, but, that is not acceptable to our customer.

Let me know if I can provide additional files or information.

Thank you very much ...

John Calderbank

[Wordinator_table_of_contents.swpx.txt](https://github.com/drmacro/wordinator/files/7463689/Wordinator_table_of_contents.swpx.txt)
[Wordinator_output_table_of_contents.docx](https://github.com/drmacro/wordinator/files/7463692/Wordinator_output_table_of_contents.docx)
[Wordinator_xsl_output_table_of_contents.docx](https://github.com/drmacro/wordinator/files/7463694/Wordinator_xsl_output_table_of_contents.docx)

**Comment by drmacro** [comment]
Here's my first stab at the SWPX markup for Toc:

```
    <toc arg-d="-" arg-x="true">
      <tocentry bookmarkRef="bm1">
        <tocentry bookmarkRef="bm2"/>
        <tocentry bookmarkRef="bm3"/>
      </tocentry>
    </toc>
```

The SWPX generator is responsible for generating the entries and the corresponding target bookmarks.

The hierarchy of the <tocentry> elements determines the ToC level.

Does this seem like a reasonable solution?

**Comment by drmacro** [comment]
I've made the first implementation.

See this pull request: https://github.com/drmacro/wordinator/pull/43

If you pull feature/issue-42-generate-toc you should be able to generate a Word document with a ToC.

The minimum requirement is to have a <toc> element in the SWPX document, which will generate an empty, but working, TOC field, which should generate a good ToC if you update the field.

If you generated <tocentry> elements with <p> elements those will be the initial text of the ToC, so you can generate a ToC with the title text and hyperlinks to the target paragraphs using normal hyperlink/bookmark mechanism.

I'm not sure the SWPX markup design is ideal--I'm starting to think it doesn't make sense to have bookmark references from the <tocentry> elements since the SWPX generator needs to put real hyperlinks in the ToC content.

In any case, with this code, if having Word actually populate the ToC after opening the doc for the first time, then all you need is a <toc> element.

**Comment by jcalder1969** [comment]
Thank you very much for the effort, Eliot ... unfortunately, I may not have been completely clear in my description of what the customer is requesting ... what they are requesting is for the table of contents to be fully updated with appropriate verbiage and page numbers without having to use a macro as they open the document ... the step of opening the document to update the table of contents is not practical on a long-term basis ... currently, we have been able to provide a table of contents with functional hyperlinks and correct verbiage but without updated page numbers - all page numbers show as "1".  We have created this by applying XSL to the Wordinator output as a second step.  The attached "Post_Wordinator_table_of_contents.docx" shows this current table of contents.  As you can see, the page numbers are not updated.  The actual page numbers are not all "1", but the table of contents refers to all page numbers as "1".  Let me know if my description is not clear.

Would you be able to advise us: is the update of the page numbers in the table of contents something that would not be possible within Wordinator?  Thank you very much ...

[Post_Wordinator_table_of_contents.docx](https://github.com/drmacro/wordinator/files/7620899/Post_Wordinator_table_of_contents.docx)

**Comment by drmacro** [comment]
At the time the Word document is generated there's no way for me to know what the page numbers will be, so it is entirely up to Word to paginate the document and then reflect the page numbers correctly.

So even if I generate the field codes that make the page number reference I wouldn't be able to populate them accurately.

As far as I can tell, Word does not automatically update page number references on open and thus there's no way to have the ToC reflect the correct page numbers automatically without using a script or manually triggering update of the ToC field.

If you print from Word you can request that the ToC be updated before the document is printed but that still requires preforming an action in Word.

**Comment by drmacro** [comment]
Minimally implemented.
